default:
  image: docker.io/library/node:20
  cache:
    key:
      files:
        - package-lock.json
    paths:
      - .npm/
      - node_modules
  before_script:
    - npm ci --cache .npm --prefer-offline

stages:
  - test
  - build
  - deploy

audit:
  stage: test
  script:
    - npm audit
  allow_failure: true

lint:
  stage: test
  script:
    - npm run lint

test:
  stage: test
  script:
    - npm run test
  artifacts:
    reports:
      junit: [junit.xml]
      coverage_report:
        coverage_format: cobertura
        path: coverage/cobertura-coverage.xml

build:
  stage: build
  script:
    - curl -o src/app/sponsor/sponsor.json $EVENT_INFO_URL
    - npm run build
    - cp out/404/index.html out/404.html
    - rm -rf out/404
  artifacts:
    paths:
      - out

pages:
  stage: deploy
  needs:
    - job: build
      artifacts: true
  script:
    - cp -r out public
  artifacts:
    paths:
      - public
  rules:
    - if: $CI_COMMIT_BRANCH == 'main'
    - if: $CI_COMMIT_BRANCH == 'develop'
  environment:
    name: staging

deploy:github-page:
  stage: deploy
  needs:
    - job: build
      artifacts: true
  script:
    - cp -r out public
    - bash ./.gitlab/scripts/deploy-github-pages.sh
  rules:
    - if: $CI_COMMIT_BRANCH == 'main'
  environment:
    name: production
