image: docker.io/library/node:20

default:
  cache:
    key:
      files:
        - package-lock.json
    paths:
      - .npm/
      - node_modules

install:
  stage: build
  script:
    - npm ci --cache .npm --prefer-offline

audit:
  stage: test
  script:
    - npm audit
  allow_failure: true

lint:
  stage: test
  script:
    - npm run lint

test:
  stage: test
  script:
    - npm run test
  artifacts:
    reports:
      junit: [junit.xml]
      coverage_report:
        coverage_format: cobertura
        path: coverage/cobertura-coverage.xml

pages:
  stage: deploy
  script:
    - npm run build
    - rm -rf public
    - cp -r out public
  artifacts:
    paths:
      - public
  rules:
    - if: $CI_COMMIT_BRANCH == 'main'
